# Generated by Django 4.1.7 on 2023-03-20 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movierating",
            old_name="numVotes",
            new_name="num_votes",
        ),
    ]
