# Generated by Django 4.1.7 on 2023-03-21 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_rename_numvotes_movierating_num_votes"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="production_status_updated",
            field=models.CharField(default="unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="link",
            name="audio_language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.language",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.language",
            ),
        ),
        migrations.AlterField(
            model_name="movieaka",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.region",
            ),
        ),
    ]
