# Generated by Django 4.1.7 on 2023-03-21 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_movie_production_status_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieaka",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.language",
            ),
        ),
    ]
