# Generated by Django 4.1.7 on 2023-03-23 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_alter_crew_birthyear_alter_crew_deathyear_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="crew",
            old_name="birthYear",
            new_name="birth_year",
        ),
        migrations.RenameField(
            model_name="crew",
            old_name="deathYear",
            new_name="death_year",
        ),
    ]
