# Generated by Django 4.1.7 on 2023-03-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_alter_movie_bottom_100_rank_alter_movie_end_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="aspect_ratio",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="production_status_updated",
            field=models.CharField(default="unknown", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="score",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
