# Generated by Django 4.1.7 on 2023-03-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0010_alter_movie_original_air_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="crew",
            name="primaryName",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="data_source",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="quality",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="resolution",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="aspect_ratio",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="box_office_budget",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="color",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="original_air_date",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="original_title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="movie",
            name="primary_title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="movie",
            name="production_status",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="production_status_updated",
            field=models.CharField(default="unknown", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="score",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="movieaka",
            name="attributes",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="movieaka",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="movieaka",
            name="types",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="movieboxofficeopening",
            name="amount",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="moviecrew",
            name="category",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="moviecrew",
            name="job",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="moviesoundmix",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
