# Generated by Django 4.1.7 on 2023-03-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0011_alter_certificate_name_alter_country_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="box_office_cumulative_worldwide_gross",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title_type",
            field=models.CharField(
                choices=[
                    ("movie", "movie"),
                    ("tvMovie", "tvMovie"),
                    ("video", "video"),
                ],
                max_length=255,
            ),
        ),
    ]
