# Generated by Django 4.1.7 on 2023-03-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0012_alter_movie_box_office_cumulative_worldwide_gross_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crew",
            name="primaryName",
        ),
        migrations.AddField(
            model_name="crew",
            name="primary_name",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="crew",
            name="primary_profession",
            field=models.CharField(default="unknown", max_length=255),
        ),
    ]
