# Generated by Django 4.1.7 on 2023-03-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0013_remove_crew_primaryname_crew_primary_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crew",
            name="primary_profession",
            field=models.CharField(default="unknown", max_length=255, null=True),
        ),
    ]
