# Generated by Django 4.1.7 on 2023-03-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0014_alter_crew_primary_profession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="original_title",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="primary_title",
            field=models.TextField(),
        ),
    ]
