# Generated by Django 4.1.7 on 2023-03-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0015_alter_movie_original_title_alter_movie_primary_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crew",
            name="primary_name",
            field=models.TextField(default="unknown"),
        ),
        migrations.AlterField(
            model_name="movieaka",
            name="attributes",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="movieaka",
            name="title",
            field=models.TextField(max_length=255),
        ),
    ]
