# Generated by Django 4.1.7 on 2023-03-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0018_alter_link_image_url_alter_link_link_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="attributes",
            field=models.JSONField(null=True),
        ),
    ]
