# Generated by Django 4.1.7 on 2023-03-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0019_alter_link_attributes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="production_status_updated",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="score",
            field=models.FloatField(default=0, null=True),
        ),
    ]
