# Generated by Django 4.1.7 on 2023-04-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0020_alter_movie_production_status_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviecrew",
            name="category",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="moviecrew",
            name="job",
            field=models.TextField(null=True),
        ),
    ]
