# Generated by Django 4.1.7 on 2023-04-03 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0021_alter_moviecrew_category_alter_moviecrew_job"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movierating",
            old_name="averageRating",
            new_name="average_rating",
        ),
    ]
