# Generated by Django 4.1.7 on 2023-04-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0022_rename_averagerating_movierating_average_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movierating",
            name="average_rating",
            field=models.FloatField(),
        ),
    ]
