# Generated by Django 4.1.7 on 2023-04-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0023_alter_movierating_average_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviekeyword",
            name="ordering",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="movievideo",
            name="ordering",
            field=models.IntegerField(default=1),
        ),
    ]
