# Generated by Django 4.1.7 on 2023-04-03 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0025_moviecertificate_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviecertificate",
            name="certificate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.certificate",
            ),
        ),
        migrations.AlterField(
            model_name="moviecertificate",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.country",
            ),
        ),
    ]
