# Generated by Django 4.1.7 on 2023-04-25 20:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_alter_moviecertificate_certificate_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='movie',
            managers=[
                ('main_movies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
