# Generated by Django 4.1.7 on 2023-05-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_alter_movie_managers_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='top_indian_rank',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='top_popular_rank',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='moviegenre',
            name='top_50_rank',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
